name: Environments
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        description: 'Environment name'
        required: false
        default: test
jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ vars.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
