name: Manual matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 20
          - os: ubuntu-22.04
            node-version: 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "${RUNNER_OS}" && node --version
