name: Sequential jobs
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo "First job completed"
  second:
    runs-on: ubuntu-latest
    needs: [first]
    steps:
      - run: sleep 5 && echo "Second job completed"
  third:
    runs-on: ubuntu-latest
    needs: [second]
    steps:
      - run: sleep 5 && echo "Third job completed"
