name: Test
on:
  pull_request:
    paths: ['go/**/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4       # step 1
      - uses: actions/setup-go@v5       # step 2
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go  # step 3
